name : Latex
on : 
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install latex
        run: sudo apt-get install texlive-latex-base
      - name: compiler latex
        run: pdflatex test.tex
      
 
    
   
  
