name : Latex
on : 
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pdf-latex
        run: sudo apt-get install texlive-latex-base
        run: pdflatex test.tex
      
 
    
   
  
