name: test PDF  

on : 
  push:
    branches:
      - main
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      
      - name: Commit and Push new file         
        run:  |   
          git config user.name qdumont           
          git config user.email quentin.dumont@etu.unistra.fr          
          git add *.pdf          
          git commit -m "add PDF file"           
          git push
