name: test PDF  

on : 
  push:
    branches:
      - main
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        run: latexmk -pdf -bibtex ${{ env.FILE }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
